Document: promogest
Title: Debian promogest Manual
Author: <insert document author here>
Abstract: This manual describes what promogest is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/promogest/promogest.sgml.gz

Format: postscript
Files: /usr/share/doc/promogest/promogest.ps.gz

Format: text
Files: /usr/share/doc/promogest/promogest.text.gz

Format: HTML
Index: /usr/share/doc/promogest/html/index.html
Files: /usr/share/doc/promogest/html/*.html

  
